services:
	- type: web
		name: pms-cgc-u-backend
		env: node
		plan: free
		buildCommand: rm -rf node_modules package-lock.json && npm install
		startCommand: node server.js
		autoDeploy: true
		rootDir: backend
