services:
  - type: web
    name: pms-cgc-u-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: YOUR_MONGODB_ATLAS_URI
