<<<<<<< HEAD
services:
  - type: web
    name: pms-cgc-u-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: YOUR_MONGODB_ATLAS_URI
=======
# This file was used for Render deployment. It is not needed for Vercel serverless API hosting.
>>>>>>> a95c41c (Refactor backend for Vercel serverless API deployment; remove Express server and Render config)
